<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\n  "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n  <head>\n
   <title>TypeError: \'list\' object is not callable // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">\n    <!-- We need to make sure this has a favicon so that the debugger does not by\n         accident trigger a request to /favicon.ico which might change the application\n         state. -->\n    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>\n    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script type="text/javascript">\n      var TRACEBACK = 140048490193528,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          SECRET = "825gsSL6RIJiSDRFsI1H";\n    </script>\n  </head>\n  <body>\n    <div class="debugger">\n<h1>builtins.TypeError</h1>\n<div class="detail">\n  <p class="errormsg">TypeError: \'list\' object is not callable</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  \n  <ul><li><div class="frame" id="frame-140048490193192">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1836</em>,\n      in <code class="function">__call__</code></h4>\n  <pre>return self.wsgi_app(environ, start_response)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194088">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1820</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <pre>response = self.make_response(self.handle_exception(e))</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194144">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask_cors/extension.py"</cite>,\n      line <em class="line">161</em>,\n      in <code class="function">wrapped_function</code></h4>\n  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194032">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1403</em>,\n      in <code class="function">handle_exception</code></h4>\n  <pre>reraise(exc_type, exc_value, tb)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194256">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/_compat.py"</cite>,\n      line <em class="line">33</em>,\n      in <code class="function">reraise</code></h4>\n  <pre>raise value</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194200">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1817</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <pre>response = self.full_dispatch_request()</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194368">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1477</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <pre>rv = self.handle_user_exception(e)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194424">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask_cors/extension.py"</cite>,\n      line <em class="line">161</em>,\n      in <code class="function">wrapped_function</code></h4>\n  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194312">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1381</em>,\n      in <code class="function">handle_user_exception</code></h4>\n  <pre>reraise(exc_type, exc_value, tb)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194536">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/_compat.py"</cite>,\n      line <em class="line">33</em>,\n      in <code class="function">reraise</code></h4>\n  <pre>raise value</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194480">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1475</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <pre>rv = self.dispatch_request()</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194648">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1461</em>,\n      in <code class="function">dispatch_request</code></h4>\n  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194704">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask_cors/decorator.py"</cite>,\n      line <em class="line">128</em>,\n      in <code class="function">wrapped_function</code></h4>\n  <pre>resp = make_response(f(*args, **kwargs))</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194592">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/helpers.py"</cite>,\n      line <em class="line">183</em>,\n      in <code class="function">make_response</code></h4>\n  <pre>return current_app.make_response(args)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490193416">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/flask/app.py"</cite>,\n      line <em class="line">1577</em>,\n      in <code class="function">make_response</code></h4>\n  <pre>rv = self.response_class.force_type(rv, request.environ)</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490194872">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py"</cite>,\n      line <em class="line">827</em>,\n      in <code class="function">force_type</code></h4>\n  <pre>response = BaseResponse(*_run_wsgi_app(response, environ))</pre>\n</div>\n\n<li><div class="frame" id="frame-140048490193584">\n  <h4>File <cite class="filename">"/usr/local/lib/python3.6/site-packages/werkzeug/test.py"</cite>,\n      line <em class="line">855</em>,\n      in <code class="function">run_wsgi_app</code></h4>\n  <pre>app_iter = app(environ, start_response)</pre>\n</div>\n</ul>\n  <blockquote>TypeError: \'list\' object is not callable</blockquote>\n</div>\n\n<div class="plain">\n  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">\n    <p>\n      <input type="hidden" name="language" value="pytb">\n      This is the Copy/Paste friendly version of the traceback.  <span\n      class="pastemessage">You can also paste this traceback into\n      a <a href="https://gist.github.com/">gist</a>:\n      <input type="submit" value="create paste"></span>\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in wsgi_app\n    response = self.make_response(self.handle_exception(e))\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1403, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 183, in make_response\n    return current_app.make_response(args)\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1577, in make_response\n    rv = self.response_class.force_type(rv, request.environ)\n  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 827, in force_type\n    response = BaseResponse(*_run_wsgi_app(response, environ))\n  File "/usr/local/lib/python3.6/site-packages/werkzeug/test.py", line 855, in run_wsgi_app\n    app_iter = app(environ, start_response)\nTypeError: \'list\' object is not callable</textarea>\n  </form>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1836, in __call__\n    return self.wsgi_app(environ, start_response)\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in wsgi_app\n    response = self.make_response(self.handle_exception(e))\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1403, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 183, in make_response\n    return current_app.make_response(args)\n  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1577, in make_response\n    rv = self.response_class.force_type(rv, request.environ)\n  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 827, in force_type\n    response = BaseResponse(*_run_wsgi_app(response, environ))\n  File "/usr/local/lib/python3.6/site-packages/werkzeug/test.py", line 855, in run_wsgi_app\n    app_iter = app(environ, start_response)\nTypeError: \'list\' object is not callable\n\n-->\n
